### PR TITLE
Add initial docs

### PR DESCRIPTION
**Pull request by jcrist**
Very rough, just initial sphinx setup.

### CODE REVIEW

**Comment by mrocklin** [comment]
@jcrist did you want to deploy with RTD or Doctr?

**Comment by jcrist** [comment]
Either or. Doctr was nice for skein because building it is slow. Since this is pure python it's easier.

**Comment by mrocklin** [comment]
OK.  I'm inclined towards RTD, mostly due to familiarity.  Any objection to
merging this and starting rtd up?

**Comment by jcrist** [comment]
Fine by me.

**Pull request merged**
