### PR TITLE
Adding gcp-dataproc tutorial to dask-yarn documentation

### PR DESCRIPTION
**Pull request by bradmiro**
Including a guide for how to get up and running with Dask-Yarn on Google Cloud Dataproc.

### CODE REVIEW

**Comment by bradmiro** [comment]
@jcrist I'm not overly familiar with Sphinx, but I wasn't able to figure out how to add this page to the TOC bar for other pages. Do I need to manually add these, or can these be rebuilt somehow?

**Comment by martindurant** [comment]
This PR is failing on lint: please run `black`.
I realise that this appears to be because of a change in the CI configuration, rather than anything added in this PR.

To your question: adding the file int he TOC list in index ought to be enough to have it appear in the sidebar.

**Comment by bradmiro** [comment]
@martindurant I added the reformatted file dask_yarn/core.py to this PR, as it seems to pass lint with this correction. Happy to revert this before merging if it's preferred to be corrected in a separate PR.

**Comment by jcrist** [comment]
Thanks @bradmiro!

**Pull request merged**
