### PR TITLE
Update dask and distributed requirements

### LINKED ISSUE #29: Update to work with distributed >= 0.23.0
Hi
I'm running with the following versions

> dask_yarn = 0.3.1
> dask = 0.19.3
> distributed = 1.23.3
> skein = 0.1.1

I'm successfully running the following code:
```
from  dask_yarn import YarnCluster
from dask.distributed import Client
cluster = YarnCluster(environment = 'testDask.tar.gz', worker_vcores=4, worker_memory='4GB', n_workers=16, name='task1')
client = Client(cluster)
client.get_versions(check=True)
```

> {'scheduler': {'host': (('python', '3.6.6.final.0'),
>    ('python-bits', 64),
>    ('OS', 'Linux'),
>    ('OS-release', '4.4.73-5-default'),
>    ('machine', 'x86_64'),
>    ('processor', 'x86_64'),
>    ('byteorder', 'little'),
>    ('LC_ALL', 'POSIX'),
>    ('LANG', 'en_US.UTF-8'),
>    ('LOCALE', 'None.None')),
>   'packages': {'required': (('dask', '0.19.3'),
>     ('distributed', '1.23.3'),
>     ('msgpack', '0.5.6'),
>     ('cloudpickle', '0.5.3'),
>     ('tornado', '5.1'),
>     ('toolz', '0.9.0')),
>    'optional': (('numpy', '1.15.0'),
>     ('pandas', '0.23.4'),
>     ('bokeh', '0.13.0'),
>     ('lz4', None),
>     ('dask_ml', None),
>     ('blosc', None))}},
>  'workers': {},
>  'client': {'host': [('python', '3.6.5.final.0'),
>    ('python-bits', 64),
>    ('OS', 'Linux'),
>    ('OS-release', '4.4.73-5-default'),
>    ('machine', 'x86_64'),
>    ('processor', 'x86_64'),
>    ('byteorder', 'little'),
>    ('LC_ALL', 'None'),
>    ('LANG', 'en_US.UTF-8'),
>    ('LOCALE', 'en_US.UTF-8')],
>   'packages': {'required': [('dask', '0.19.3'),
>     ('distributed', '1.23.3'),
>     ('msgpack', '0.5.6'),
>     ('cloudpickle', '0.5.3'),
>     ('tornado', '5.1'),
>     ('toolz', '0.9.0')],
>    'optional': [('numpy', '1.15.0'),
>     ('pandas', '0.23.4'),
>     ('bokeh', '0.13.0'),
>     ('lz4', None),
>     ('dask_ml', None),
>     ('blosc', None)]}}}
> 

but when running:
`cluster.scale(8)`

I'm getting the following error
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-6e6c3e46d9a8> in <module>()
----> 1 cluster.scale(8)
/opt/anaconda3/lib/python3.6/site-packages/dask_yarn/core.py in scale(self, n)
    315 
    316             if n_to_delete:
--> 317                 to_close = self._select_workers_to_close(n_to_delete)
    318                 self.scale_down(to_close)
    319 
/opt/anaconda3/lib/python3.6/site-packages/dask_yarn/core.py in _select_workers_to_close(self, n)
    285         worker_info = client.scheduler_info()['workers']
    286         # Sort workers by memory used
--> 287         workers = sorted((v['memory'], k) for k, v in worker_info.items())
    288         # Return just the ips
    289         return [w[1] for w in workers[:n]]
/opt/anaconda3/lib/python3.6/site-packages/dask_yarn/core.py in <genexpr>(.0)
    285         worker_info = client.scheduler_info()['workers']
    286         # Sort workers by memory used
--> 287         workers = sorted((v['memory'], k) for k, v in worker_info.items())
    288         # Return just the ips
    289         return [w[1] for w in workers[:n]]
KeyError: 'memory'

```

any ideas?

### PR DESCRIPTION
**Pull request by jcrist**
- Bump dask minimum version
- Bump distributed minimum version
- Bump skein minimum version
- Update to work with distributed 1.23.0 (Fixes #29)
- Remove patch for old versions of dask

### CODE REVIEW

**Comment by sephib** [comment]
Hi,
What should be the most stable versions to run dask/dask-yarn/distributed/pyarrow?
Due to issue #29 I downgraded to:

> distributed: 1.22.1
> dask:          0.18.2
> dask-core:  0.18.2
> dask-yarn:  0.3.1
> pyarrow:     0.11

Now I'm getting errors while trying to read csv files from hdfs with pyarrow...
> ArrowIOError: Unable to load libhdfs

I'm able to read the file using `dask` (but not `dask-yarn`). 
i've reviewed issue #20 - and all the configurations look to be OK.

Any suggestions?

**Comment by jcrist** [comment]
#29 is now fixed on `dask-yarn` master, if you care to install from github. I plan to push a bugfix release sometime this week.

> Now I'm getting errors while trying to read csv files from hdfs with pyarrow...

Without more information I'm unable to help you. A full traceback at minimum would be needed. For most users, setting `ARROW_LIBHDFS_DIR` locally, as well as providing `worker_env={'ARROW_LIBHDFS_DIR': ...}` to the `YarnCluster` constructor should fix any issues you have.

**Comment by sephib** [comment]
Thx for your time and response.
Hope to update in the next coming days

**Comment by jcrist** [comment]
`dask-yarn` version 0.3.2 is now released. Available on PyPI, and shortly on conda-forge.

**Comment by sephib** [comment]
THX!
Using the ` worker_env={'ARROW_LIBHDFS_DIR': ...}`  did the job!
Once `dask-yarn/linux64` version 0.3.2 is on  conda-forge I'll be happy to try it out.
Thx again for your time

**Comment by jcrist** [comment]
Glad to hear it. And 0.3.2 is already on conda-forge.

**Pull request merged**
