### PR TITLE
rename ncores to nthreads

### LINKED ISSUE #77: KeyError: 'ncores'
I was unable to copy and paste the stacktrace but here's a screenshot:

Screen Shot 2019-07-02 at 8 36 40 PM

### PR DESCRIPTION
**Pull request by AlJohri**
fixes #77

### CODE REVIEW

**Comment by AlJohri** [comment]
Test failed on:

```
dask_yarn/tests/test_cli.py::test_cli_submit_and_status[good-SUCCEEDED-Done!] Collecting packages...
Packing environment at u'/home/testuser/miniconda/envs/test-environment' to 'dask-yarn-py27.tar.gz'
[########################################] | 100% Completed | 12.8s
19/07/03 03:08:00 INFO client.RMProxy: Connecting to ResourceManager at master.example.com/172.18.0.4:8032
19/07/03 03:08:00 INFO skein.Driver: Driver started, listening on 38146
FAILED
```

Any ideas @TomAugspurger?

**Comment by TomAugspurger** [comment]
Not sure. Hopefully @jcrist can provide some help.

**Comment by jcrist** [comment]
Apologies for the delay here, I've been out-of-office (vacation, then SciPy). Thanks for the fix, I've pushed another commit making this backwards compatible and fixing up some changes for the most recent release of distributed. Will merge and release on tests pass.

**Comment by jcrist** [comment]
This has now been released as part of version `0.6.2`. Thanks for the PR!

**Pull request merged**
