### PR TITLE
[WIP] Add `dask-yarn submit` command

### LINKED ISSUE #15: Add a CLI for submitting batch jobs
This would probably look like

```console
$ dask-yarn submit myscript.py [options...]
```

It would submit a YARN job with an additional service running the user's script. This would allow `dask-yarn` to submit scripts to run fully on the cluster, mirroring `spark-submit` in `cluster` mode. The command could either exit immediately (leaving tracking of application success/failure to other tools), or log to the console.

### PR DESCRIPTION
**Pull request by jcrist**
Adds a submit command, which submits a script to run independently on
the cluster.

Still needs some iteration on the api, but functionally already works.

Fixes #15.

### CODE REVIEW

**Comment by jcrist** [comment]
## Use Case

This is for running applications on a cluster in a way that *nothing* runs on the edge node. This is most useful for applications that are being run in production (e.g. ETL workflows), rather than interactive applications. This could be used with Apache Oozie or Cron to schedule recurrent jobs in a scripted way, leaving the edge node free for other users. For a Spark comparison, this is similar to `spark-submit` when running in cluster mode on YARN.

## Intended workflow

1. A user writes a script, creating a `YarnCluster` from an existing cluster using the `YarnCluster.from_current` method. This script will run on the cluster.

```python
from dask_yarn import YarnCluster
from dask.distributed import Client
from dask.datasets import timeseries

print("Connecting to cluster")
cluster = YarnCluster.from_current()
print("Attaching client")
client = Client(cluster)

print("Creating timeseries")
ddf = timeseries()
print("Writing out to parquet")
ddf.to_parquet('hdfs:///user/testuser/timeseries.parq')
print("Done!")
```

2. The user then packages the required environment using `conda-pack`

```
$ conda pack --force -o environment.tar.gz
Collecting packages...
Packing environment at '/home/testuser/miniconda/envs/dask-yarn-py37' to 'environment.tar.gz'
[########################################] | 100% Completed | 22.3s
```

3. The application can then be submitted to the cluster. This returns a YARN application id, which can be used with other tools (getting logs, tracking progress, etc...).

```
$ appid=`dask-yarn submit \
--environment environment.tar.gz \
--worker-count 2 \
--worker-vcores 1 \
--worker-memory 512MiB \
--client-memory 256MiB \
--scheduler-memory 512MiB \
test.py`

18/10/26 03:20:15 INFO client.RMProxy: Connecting to ResourceManager at master.example.com/172.22.0.4:8032
18/10/26 03:20:15 INFO skein.Daemon: Daemon started, listening on 33119
18/10/26 03:20:16 INFO skein.Daemon: Uploading application resources to hdfs://master.example.com:9000/user/testuser/.skein/application_1540479500228_0035
18/10/26 03:20:18 INFO skein.Daemon: Submitting application...
18/10/26 03:20:18 INFO impl.YarnClientImpl: Submitted application application_1540479500228_0035
18/10/26 03:20:18 INFO skein.Daemon: Daemon shut down

$ echo $appid
application_1540479500228_0035
```

4. Getting the logs for just the client:

```
$ yarn logs -applicationId application_1540479500228_0035 -nodeAddress worker.example.com_36889 -containerId container_1540479500228_0035_01_000005
18/10/26 03:40:08 INFO client.RMProxy: Connecting to ResourceManager at master.example.com/172.22.0.4:8032
LogType:dask.client.log
Log Upload Time:Fri Oct 26 03:35:03 +0000 2018
LogLength:2067
Log Contents:
+ source environment/bin/activate
++ _conda_pack_activate
++ local _CONDA_SHELL_FLAVOR
++ '[' -n x ']'
++ _CONDA_SHELL_FLAVOR=bash
++ local script_dir
++ case "$_CONDA_SHELL_FLAVOR" in
+++ dirname environment/bin/activate
++ script_dir=environment/bin
+++ cd environment/bin
+++ pwd
++ local full_path_script_dir=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment/bin
+++ dirname /var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment/bin
++ local full_path_env=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment
+++ basename /var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment
++ local env_name=environment
++ '[' -n '' ']'
++ export CONDA_PREFIX=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment
++ CONDA_PREFIX=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment
++ export _CONDA_PACK_OLD_PS1=
++ _CONDA_PACK_OLD_PS1=
++ PATH=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PS1='(environment) '
++ case "$_CONDA_SHELL_FLAVOR" in
++ hash -r
++ local _script_dir=/var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment/etc/conda/activate.d
++ '[' -d /var/tmp/hadoop-yarn/local/usercache/testuser/appcache/application_1540479500228_0035/container_1540479500228_0035_01_000005/environment/etc/conda/activate.d ']'
+ python test.py
Connecting to cluster
Attaching client
Creating timeseries
Writing out to parquet
Done!
```

**Comment by jcrist** [comment]
An alternative/additional implementation might start a longer running cluster first, and then involve submitting applications to that existing cluster. Workflow would be (pseudocode):

```
# Start a longer running dask cluster
$ appid=`dask-yarn cluster start --worker-count 10 ...

# Submit scripts to that cluster
$ dask-yarn submit $appid script.py

# Eventually shutdown the cluster
$ dask-yarn cluster stop $appid
```

Functionality similar to this already exists with the old `dask-submit`/`dask-remote` commands in `dask.distributed`. I'm not sure what would be more useful to people - what's already in this PR is more like how `spark-submit` works, which is probably what people are used to.

**Comment by quasiben** [comment]
I think the [Intended Workflow](https://github.com/dask/dask-yarn/pull/35#issuecomment-434830621) outlined above is really great and what I suspect most users will expect.  It might be nice to extend that particular case with an option to leave the cluster running but that is purely icing.  If you leave the cluster running you functionally have the equivalent of the alternative implementation but with a single command

**Comment by danielfrg** [comment]
Agree with Ben, I think the intended workflow its something users are familiar from spark (as you mention) and the use case of having completely independent jobs running is on point as people start to "productionalize" and automate their pipelines.

In general I like the fact that is very similar to `spark-submit`.

I like the `YarnCluster.from_current()` API, it reminds me of creating a kubernetes client from inside a Pod running in kubernetes. +1

**Comment by jcrist** [comment]
Ok, this is currently passing (at least locally). I've added 3 commands:

- `dask-yarn submit`: submit an application
- `dask-yarn status`: get the status of an application
- `dask-yarn kill`: kill a running application

The cluster should be properly shutdown when the client process exits, with the final status of the application determined from the exit code of the process. Note that this is a bit of a hack for now, as this has to be implemented on the Python side. In the future I'd like to find a way to make this part of Skein, which should make it much more robust. It works fine for now though.

**Comment by jcrist** [comment]
Ok, this is in. I did a bit of a refactor here, and the "hack" described above has been downgraded to "less-than-optimal-but-still-ok". I do feel less pressured to change things now, but at some point in the future it may be good to push this handling into the application master.

**Pull request merged**
